- name: configure frent server
  hosts: frentend
  become: yes
  tasks:
  - name: install nginx server
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: enable and start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
    
  - name: delete html direcotry
    ansible.builtin.file:
     path:  /usr/share/nginx/html
     state: absent

  - name: create html direcotry
    ansible.builtin.file:
     path:  /usr/share/nginx/html
     state: directory   
 
  - name: dowmload frontend file
    ansible.builtin.get_url: 
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: unzip frontend code
    ansible.builtin.unarchive: 
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes   

  - name : copy backend services 
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf
 
  - name: restart nginx
    ansible.builtin.service:
      state: restarted
      name: ngnix
        
