- name: configured mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed 

  - name: start the mysql-server  
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes